---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: example-admission-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-admission-controller
  labels:
    app: example-admission-controller
  namespace: example-admission-controller
spec:
  selector:
    matchLabels:
      app: example-admission-controller
  template:
    metadata:
      labels:
        app: example-admission-controller
    spec:
      containers:
      - name: example-admission-controller
        image: example-admission-controller-image
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: certs
          mountPath: "/etc/certs/"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: example-admission-controller-cert
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxekNDQWI4Q0ZGMkRXK3c5UXpPN3lNMnlPbEU0RDFBSVU0NEpNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3gKSmpBa0JnTlZCQU1NSFd4aUxYWmhiR2xrWVhSdmNpNXNZaTEyWVd4cFpHRjBiM0l1YzNaak1CNFhEVEkwTURFeQpPVEl3TkRZME5Gb1hEVE0wTURFeU5qSXdORFkwTkZvd0tERW1NQ1FHQTFVRUF3d2RiR0l0ZG1Gc2FXUmhkRzl5CkxteGlMWFpoYkdsa1lYUnZjaTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUIKQVFDZW5ibDJkbHc5c3QzWVY2b3ErWTAxazFFcUNOY3BGam5GWXhsUDdHMFFUejVDckNXL1hQVmRsVTJWWkFJSwp0dUpIQjdFU240cC94YXRvYWdTd25TNTlnVkZhcjYzY3JueEdWZUVaa2hEbWVCbW5hR2I1QWlNRnJhWUd6SGtJCi9JS3dqMnJjbWlYL1dPWlhTeEFudHgrNkd3T2xvM3ZEYXdLcGpISnV3RFQzcWlqQkpRd0hnREF3YTlyYmI4bWgKR0N1L2NZTHFzOGdJRVp5LzlTTEw1RCtlUGQvbVJhVzJjUEN2dThpZXRxRUp3TlNEUnlHbTMwYlJsTjFpRkVjaApkaVBIZThJTjd4Um15djNqTDV2S1JheTZ2OWx3U2tVZmJXTE11ZXFmZnp4RG0yL0FhUkxyZ3RhblRvd1JvakFKCkVBSkVmdDFqOTZXQ0lvL3dSZXhpNk5TdkFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUI1RXhlQ0QKbDlSS05EVVRVYVFhQStNT2M2ZTJYOVFkcEhjQ3J1N0F0eHNkbXNTVkJqSlNVaHF3a0JsUTNGL0JnRHgwZXh0VAp0bzdQOUdQd2JiNjFqWTNTUEtuN2FnbEQ1emVJZXhJRjUzcFZURHFWL0tnK25WYjlFdHF5K01aU05ZcFdhZGtpCnZZL3dQK2N2Q2g1bHE0WXI5NmtNUTF1SUdpS2V3amtoQUNkTXZiWkV1bGhMOFRmRmtjMWdPWEtNdXpVMzU5K0IKOHRuWHo5STlIUjRMRUExRDlXYVZyeXNERFFXbUJvbDJ6TzRTWFg4eXpxZkFsZmpWWUJCTnVXQi8xRTdFOVA5UwpBaUlvMGhGeE9WOWdPTWc2MDJvRHk3OUoydkhZV25KUE9tRFIramo4Vlp3TkdZcU1JUm5WNk9rZ042UC9WaEQ3Ck9scjVPV2ZLRDBvcG9JMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2VuYmwyZGx3OXN0M1kKVjZvcStZMDFrMUVxQ05jcEZqbkZZeGxQN0cwUVR6NUNyQ1cvWFBWZGxVMlZaQUlLdHVKSEI3RVNuNHAveGF0bwphZ1N3blM1OWdWRmFyNjNjcm54R1ZlRVpraERtZUJtbmFHYjVBaU1GcmFZR3pIa0kvSUt3ajJyY21pWC9XT1pYClN4QW50eCs2R3dPbG8zdkRhd0twakhKdXdEVDNxaWpCSlF3SGdEQXdhOXJiYjhtaEdDdS9jWUxxczhnSUVaeS8KOVNMTDVEK2VQZC9tUmFXMmNQQ3Z1OGlldHFFSndOU0RSeUdtMzBiUmxOMWlGRWNoZGlQSGU4SU43eFJteXYzagpMNXZLUmF5NnY5bHdTa1VmYldMTXVlcWZmenhEbTIvQWFSTHJndGFuVG93Um9qQUpFQUpFZnQxajk2V0NJby93ClJleGk2TlN2QWdNQkFBRUNnZ0VBUUlhL25TNlhaYzR2SzhTMkNGZVBGNTEvcGs4RVlNV1c2UExncUQveE9uSlMKVE1ORmMrejRNSUw5bGVtaVh3TjVXQllMOWh5TE5tR08wcUpXbUJiSmcrc28wbkNubFNBeWxGWjVoWEtEaDQ2UwpPU1ZpeHFnVTRVbDhRa1hLYzFwdVBDK0w5SVNOTXF6U3YrNWNleHVuUDRtZjJUR0J0c1VBeDBMSWhyK1FqTE82Cm9rc2wxSGJjRzlqSWduZVNnUnhqRzVYOVNUVEZtV0tqU2RjRGNyOFZ3OTYwN0lkMWNRTVhlRjlJc29KWnpTZG4KREpFckoxNS9IKy90eDFkdTczNlI3ZTZJSmwrV0xMOVNIdGUrNy9MWlJsZ1dvWkN1WW5hT2ViNmFKT2g4WFNvVApQaVgzdi81M3h5OWFZd3ZiVG80eUxyMkxmY0NTZm9sV0hKS2VYS2JDaVFLQmdRQzE1TUw0c282QWVLRWl2QXhjCndZbjdyOVA2VUhZbXZtUnFMTlZjMUpUeUxFQXF1RWUwckdDSWtIU3NKNzdXRlQ5TnkwQ1RjdFNUVjhMRHhVZWsKQi8wVFpodjdVeHZVdkxwTEgvRVFBNTFZLzY2TGhXYk9seEhIaHBCbXpsZWFEZXVFZGszZk9VR1hDL213TEhLRQp2L2FvUGpzMGZDdWxsNWtVSzZFNXVEQ0tzd0tCZ1FEZlBTZVJzRlJtUStDSUdiUUQ5dU94R21OTzNSSUUrWVExCnB3SE5kVHhFTUhqSGNNTElucXQwc2tjY1N6cnRZaGVUVEQyWTJNY2JpZUpvTTkzQlFDZVlvT1dVZHNta01ja0sKSHRibldCQXpKaTg1Zk5zU1FkVFhyWGhESnVlVGFCOWJRYmkrWEJmN0tEc0dJL0ZicVZYZ05xNHV2dFYrWktoTQp2M0VQQzZhOEZRS0JnRmpkSkd3QVFDSi96S2w5bWNTUFFXeFhJSWNBWEZqZFY0MlB6Y1dHamlZcWZFYml0UldOCnliT3ViM0hVRVNYaVI0VW9NYXBYeFljZXJ5YVo4VUF3THZJVlJzSm9mZ1pYRmVTeC9FSElva3ppelZHWW9QdDUKVHRSZDU1cHlZTllBeXZseUd1VmR3YStieUNiTDhEN3UwZ0NzTnB5VHRYYzNNekJwaUdEOG5hcUZBb0dBQm9RcAplSVkySUhvUXZzaEpTZWhXQXlCckQ2MUNUbVRlS0JiRTViTnJXKzR5U0ZnUlIzdmlNMWpVM0kyUm5jWkVPK2Q0CjBOSmJGWUd6MnlqUWEwaXRIelpySFNkT2dYMTJpZFlXbmRBalFPcjNhKzBxRStGYURpV2hJZ3lycTlEWlFYZXMKcGRuWVZWdDZSWmFjLy9qMGFjUU8xNHg0Zk9VQlNLUTU3NTkrY1hVQ2dZRUFoeXh0YlBwVWsvNm1oSytvS0FuYgpaVVVVbWwwejlQck1qK2lpd3YrYzF5SksyL0JCa1JGN005UjRmZWxTbHdsbmwwZ0JEdmhseUNCaW9UZ1RPQTlQCkN0VzVySExkN3hVSnZNTytiNU1vZEFIVEREaXd5RDdmOGU5Rnl3WlRBaEkvSFRWWmpoVTVRTVp5STJGcEpHNUsKbWxUU1hCMTlmS1N1TEJweUpLRTdZSlU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: example-admission-controller-cert
  namespace: example-admission-controller
type: kubernetes.io/tls
---
apiVersion: v1
kind: Service
metadata:
  name: example-admission-controller-svc
  namespace: example-admission-controller
spec:
  selector:
    app: example-admission-controller
  ports:
    - port: 443
      targetPort: 8080
  type: LoadBalancer