apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-1
  namespace: metallb-system
spec:
  addresses:
  - $IP_RANGE
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metal-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool-1